export const enableEmailVerify = false;
export const permissionCount = 3;
export const permissionVisit = 1 << 0;
export const permissionSpeak = 1 << 1;
export const permissionAdmin = 1 << 2;
export const timeLimitDefault = 1000;
export const timeLimitMax = 5000;
export const memoryLimitDefault = 512;
export const memoryLimitMax = 1024;